### PR TITLE
Documentations

### PR DESCRIPTION
**Pull request by rungwe**
- Updated the read me file
- Demonstrated a test example
- Updated package.json

### CODE REVIEW

**Comment by kibae** [comment]
Hey, @rungwe.
I've added you as a contributor to the project, let me know if you have the ID of npmjs for publishing.

**Comment by kibae** [comment]
@rungwe 
I think the typeorm-sharding-repository and nestjs-typeorm-sharding-repository should be separate, with nestjs-typeorm-sharding-repository depending on typeorm-sharding-repository.
If you develop nestjs-typeorm-sharding-repository and need to make changes to typeorm-sharding-repository, let's make them.

**Comment by rungwe** [comment]
Thanks and well noted.

After considering my requirements, which included modularisation of the library into a NestJS module, I have decided to maintain a separate fork to avoid polluting the pure TypeORM solution. You can have a look here https://github.com/rungwe/nestjs-typeorm-sharding-repository <https://github.com/rungwe/nestjs-typeorm-sharding-repository>

Once I find time, I will them contribute to your library to update the new sharing scheme I have developed.

Kind regards

**Comment by kibae** [comment]
This project might close if your project succeeds. I also use NestJS a lot. I hope your work helps many people and me. :)

**Comment by rungwe** [comment]
Okay cool, I will let you know once I publish, you could assist in testing it or be the early consumer.

**Comment by rungwe** [comment]
The project is now live on the public npm registry.  Feel free to check it out, your feedback will be very much appreciated.nest-typeorm-sharding-repositorynpmjs.comSent from my iPhoneOn 23 Apr 2024, at 16:24, Kibae Shin ***@***.***> wrote:﻿
This project might close if your project succeeds. I also use NestJS a lot. I hope your work helps many people and me. :)

**Pull request closed without merging**
